

services:
  app1:
    build:
      context: ./app
    environment:
      - APP_PORT=8081
    expose:
      - "8080"
    container_name: app1

  app2:
    build:
      context: ./app
    environment:
      - APP_PORT=8082
    expose:
      - "8080"
    container_name: app2

  app3:
    build:
      context: ./app
    environment:
      - APP_PORT=8083
    expose:
      - "8080"
    container_name: app3

  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
      - app3
